// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace perfumes.DATA.Models;

public partial class Autenticacion
{
    public int AutenticacionId { get; set; }

    public int? UsuarioId { get; set; }

    public int? RolId { get; set; }

    public virtual Role Rol { get; set; }

    public virtual Usuario Usuario { get; set; }
}