// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace perfumes.DATA.Models;

public partial class HistorialPrecio
{
    public int HistorialPrecioId { get; set; }

    public int? ProductoId { get; set; }

    public int? UsuarioId { get; set; }

    public decimal PrecioAnterior { get; set; }

    public decimal PrecioNuevo { get; set; }

    public DateTime? FechaCambio { get; set; }

    public virtual Producto Producto { get; set; }

    public virtual Usuario Usuario { get; set; }
}