// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace perfumes.DATA.Models;

public partial class MovimientosStock
{
    public int MovimientoId { get; set; }

    public int? ProductoId { get; set; }

    public int? UsuarioId { get; set; }

    public string TipoMovimiento { get; set; }

    public int Cantidad { get; set; }

    public DateTime? FechaMovimiento { get; set; }

    public string Motivo { get; set; }

    public virtual Producto Producto { get; set; }

    public virtual Usuario Usuario { get; set; }
}