// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace perfumes.DATA.Models;

public partial class Producto
{
    public int ProductoId { get; set; }

    public string NombreComercial { get; set; }

    public string Marca { get; set; }

    public int? ContenidoCantidad { get; set; }

    public string UnidadMedida { get; set; }

    public int? CategoriaId { get; set; }

    public int? ProveedorId { get; set; }

    public decimal PrecioCosto { get; set; }

    public decimal PrecioVenta { get; set; }

    public int? StockActual { get; set; }

    public int? StockMinimo { get; set; }

    public string Concentracion { get; set; }

    public string NotasOlfativas { get; set; }

    public virtual Categoria Categoria { get; set; }

    public virtual ICollection<DetallesVentum> DetallesVenta { get; set; } = new List<DetallesVentum>();

    public virtual ICollection<HistorialPrecio> HistorialPrecios { get; set; } = new List<HistorialPrecio>();

    public virtual ICollection<MovimientosStock> MovimientosStocks { get; set; } = new List<MovimientosStock>();

    public virtual Proveedore Proveedor { get; set; }
}