// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace perfumes.DATA.Models;

public partial class Proveedore
{
    public int ProveedorId { get; set; }

    public string NombreEmpresa { get; set; }

    public string ContactoNombre { get; set; }

    public string Telefono { get; set; }

    public string Email { get; set; }

    public virtual ICollection<Producto> Productos { get; set; } = new List<Producto>();
}