// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace perfumes.DATA.Models;

public partial class Role
{
    public int RolId { get; set; }

    public string NombreRol { get; set; }

    public virtual ICollection<Autenticacion> Autenticacions { get; set; } = new List<Autenticacion>();
}