// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace perfumes.DATA.Models;

public partial class Usuario
{
    public int UsuarioId { get; set; }

    public int? CredencialId { get; set; }

    public int? EmpleadoId { get; set; }

    public virtual ICollection<Autenticacion> Autenticacions { get; set; } = new List<Autenticacion>();

    public virtual Credenciale Credencial { get; set; }

    public virtual Empleado Empleado { get; set; }

    public virtual ICollection<HistorialPrecio> HistorialPrecios { get; set; } = new List<HistorialPrecio>();

    public virtual ICollection<MovimientosStock> MovimientosStocks { get; set; } = new List<MovimientosStock>();

    public virtual ICollection<Venta> Venta { get; set; } = new List<Venta>();
}