// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace perfumes.DATA.Models;

public partial class Venta
{
    public int VentaId { get; set; }

    public int? UsuarioId { get; set; }

    public DateTime? FechaVenta { get; set; }

    public decimal TotalVenta { get; set; }

    public string MetodoPago { get; set; }

    public virtual ICollection<DetallesVentum> DetallesVenta { get; set; } = new List<DetallesVentum>();

    public virtual Usuario Usuario { get; set; }
}